# Generated by Django 2.2.4 on 2019-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20191218_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='calculate_method',
            field=models.CharField(choices=[('EXCRETION', 'دفعات'), ('INSTALLMENTS', 'اقساط'), ('CASH', 'كاش')], max_length=14),
        ),
        migrations.AlterField(
            model_name='worker',
            name='getting_method',
            field=models.CharField(choices=[('Distinct', 'ممتده'), ('Transaction', 'تحويل')], max_length=12),
        ),
    ]
