# Generated by Django 2.2.4 on 2019-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20191218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
