# Generated by Django 2.2.4 on 2019-12-19 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20191218_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='unpaid_money',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='unpaid_money',
        ),
        migrations.AddField(
            model_name='worker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
