# Generated by Django 2.2.4 on 2019-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20191219_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='company_number',
        ),
        migrations.AddField(
            model_name='worker',
            name='id_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
