# Generated by Django 2.2.4 on 2019-12-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20191220_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='no_of_installment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='paid_money',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_money',
        ),
        migrations.AddField(
            model_name='worker',
            name='unpaid_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='my_app.Worker'),
        ),
    ]
