# Generated by Django 2.2.4 on 2019-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20191220_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='calculate_method',
            field=models.CharField(choices=[('دفعات', 'دفعات'), ('اقساط', 'اقساط'), ('كاش', 'كاش')], max_length=14),
        ),
        migrations.AlterField(
            model_name='worker',
            name='getting_method',
            field=models.CharField(choices=[('ممتده', 'ممتده'), ('تحويل', 'تحويل')], max_length=12),
        ),
    ]
