# Generated by Django 2.2.4 on 2019-12-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20191222_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='commercial_exp',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='company_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='worker',
            name='company_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='worker',
            name='exp_need',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job_type',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='worker',
            name='nationality',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='paid_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='resp_user_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sponser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sponser_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='unpaid_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
